main: me.con68.bookshelfdisplayreborn.BookshelfDisplayPlugin
name: BookshelfDisplayReborn
version: "1.0"
api-version: "1.18"
description: Put books in bookshelves and read them, again!
website: https://www.spigotmc.org/resources/bookshelfdisplay.67225/
authors: [Cynadyde, con68]
depend: [ ProtocolLib ]
commands: {}
permissions:
  bookshelfdisplay.*:
    description: "Grants all plugin abilities."
    default: false
    children:
      bookshelfdisplay.view: true
  bookshelfdisplay.view:
    description: "Grants the ability to interact with bookshelves."
    default: true
